made a new component infoicontippy
devtron-labs/devtron-fe-common-lib pull request #114
Opened 2024-03-22 09:36 UTC by randhir-devtron

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-03-22 11:47 UTC, AbhishekA1509 requested changes

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Common/CustomInput/CustomInput.tsx
> +import React from 'react'
No need

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +    className += ' fcn-9 ml-8 cursor'
Do not use margin, can use ```p-0 h-20 dc__no-background dc__no-border dc__outline-none-imp``` as baseClassname

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +    switch (variant) {
Move this to util and avoid let

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +            documentationLinkText="View Documentation"
Are you sure we need to show documentationLinkText every time, we can move this to prop

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +        case 'SMALL':
use enum

2024-03-22 11:47 UTC, AbhishekA1509 commented on src/Shared/types.ts
> +export interface InfoIconTippyType {
use Pick and import type from TippyCustomized

2024-03-27 14:32 UTC, AbhishekA1509 requested changes

2024-03-27 14:32 UTC, AbhishekA1509 commented on src/Common/AppStatus/utils.ts
> +    let className: string
No need to create variable can directly return variable

2024-03-27 14:32 UTC, AbhishekA1509 commented on src/Common/Constants.ts
> +export enum TIPPY_ICON_DIM {
Move it to types.ts and rename TippySizeVariant some thing like that

2024-04-01 07:44 UTC, AbhishekA1509 commented on src/Common/AppStatus/AppStatus.tsx
> +import React from 'react'
Remove this

2024-04-01 07:45 UTC, AbhishekA1509 commented on src/Common/AppStatus/utils.ts
> +
Run prettier once

2024-04-01 07:49 UTC, AbhishekA1509 commented on src/Common/ImageTags.tsx
> +            infoText=""
no need to send this, this should be optional

2024-04-01 07:51 UTC, AbhishekA1509 commented on src/Common/Constants.ts
> +export enum TIPPY_ICON_DIM {
Remove this if not using in any place

2024-04-01 07:55 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +            className="p-0 dc__no-background dc__no-border dc__outline-none-imp flex ml-4 dc__tab-focus"
Can we remove this ml-4?

2024-04-02 09:57 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +}: Pick<
Move it to interface like export interface InfoIconTippyProps extends Pick< TippyCustomizedProps , 'heading' | ... > {dataTestid?: string}

2024-04-02 09:58 UTC, AbhishekA1509 commented on src/Common/AppStatus/utils.ts
> -
Try to have a blank linke between component and import statements for readability purpose

2024-04-02 09:59 UTC, AbhishekA1509 commented on src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx
> +    dataTestid,
Can we add a default test id

2024-04-02 12:46 UTC, AbhishekA1509 approved these changes

2024-04-12 06:18 UTC, vivek-devtron submitted a review, later dismissed

2024-04-12 07:04 UTC, vivek-devtron submitted a review, later dismissed

2024-04-14 07:57 UTC, vivek-devtron submitted a review, later dismissed

2024-04-15 07:25 UTC, vivek-devtron approved these changes

2024-04-19 09:05 UTC, vivek-devtron submitted a review, later dismissed

2024-04-19 09:45 UTC, vivek-devtron approved these changes

2024-04-19 09:46 UTC, merged