refactor: component migration
devtron-labs/devtron-fe-common-lib pull request #119
Opened 2024-04-03 08:44 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-04 09:48 UTC, eshankvaish requested changes

2024-04-04 09:48 UTC, eshankvaish commented on src/Shared/Components/header/index.ts
> +export * from './HeaderWithCreateButton'
export types as well

2024-04-04 09:48 UTC, eshankvaish commented on src/Shared/Components/header/HelpNav.tsx
> +            action: `${option.name} Clicked`,
update casing for header =>Header folder

2024-04-04 09:48 UTC, eshankvaish commented on src/Shared/Components/ButtonWIthLoader/ButtonWithLoader.tsx
> +export class ButtonWithLoader extends Component<ButtonProps> {
We have not exported anywhere, pls verify the usage after exporting for one case

2024-04-04 09:48 UTC, eshankvaish commented on src/Common/Constants.ts
> +    CONNECT_CLUSTER: 'Connect cluster',
mark deprecated as required

2024-04-08 10:41 UTC, vivek-devtron submitted a review, later dismissed

2024-04-08 11:17 UTC, eshankvaish approved these changes

2024-04-08 11:20 UTC, vivek-devtron approved these changes

2024-04-08 11:28 UTC, merged