Feat/resource scan
devtron-labs/devtron-fe-common-lib pull request #122
Opened 2024-04-04 13:56 UTC by AbhishekA1509

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-08 08:11 UTC, eshankvaish requested changes

2024-04-08 08:11 UTC, eshankvaish commented on src/Shared/constants.tsx
> +export const STRINGIFIED_TRUE = 'true'
.

2024-04-08 08:11 UTC, eshankvaish commented on src/Shared/Components/ScannedObjectBar/styles.scss
> +.scanned-object__bar {
pls use util classes

2024-04-08 11:38 UTC, AbhishekA1509 commented on package.json
>      },
Leaving as discussed

2024-04-08 11:38 UTC, AbhishekA1509 commented on src/Shared/types.ts
> +export type NodeType = keyof typeof Nodes
imported as is from dashboard

2024-04-08 12:25 UTC, AbhishekA1509 commented on src/Shared/constants.tsx
> +export const STRINGIFIED_TRUE = 'true'
Done

2024-04-08 12:25 UTC, AbhishekA1509 commented on src/Shared/Components/ScannedObjectBar/styles.scss
> +.scanned-object__bar {
imported from dashboard

2024-04-09 06:27 UTC, eshankvaish commented on src/Shared/types.ts
> +export type NodeType = keyof typeof Nodes
Please sync with QA for testing this. This seems to be a potential bug

2024-04-09 06:31 UTC, eshankvaish approved these changes
pls add the respective todo

2024-04-10 06:08 UTC, vivek-devtron submitted a review, later dismissed

2024-05-03 15:09 UTC, merged