feat: Markdown added
devtron-labs/devtron-fe-common-lib pull request #123
Opened 2024-04-05 12:04 UTC by shivani170

# Description

Markdown

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-08 07:41 UTC, eshankvaish requested changes

2024-04-08 07:41 UTC, eshankvaish commented on package.json
> -    "version": "0.0.74",
pls check the correct version

2024-04-08 07:41 UTC, eshankvaish commented on package.json
> +        "dompurify": "^3.0.2"
we would need these in dev dependencies as well

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Helper.tsx
> +            setYaml(YAML.stringify(obj, { indent: 2 }))
any specific reason for removing this?

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/CodeEditor/CodeEditor.tsx
> +                final = state.mode === 'json' ? JSON.stringify(obj, null, tabSize) : YAML.stringify(obj, { indent: 2 })
FYI this code editor is not exported at present. Also shouldn't we update the dashboard as well

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +const MarkDown = (
If migrated from dashboard, please mark the one in dashboard as deprecated

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +    setExpandableIcon: (arg0: boolean) => void,
better name for arg0

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +    ...props: any[]
- add types, also create a separate file for types
- We are not exporting the component

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +    const renderer = new marked.Renderer()
all three can be moved outside the component

2024-04-08 07:41 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +    }
Also, we can use arrow function

```suggestion
    function isReadmeInputCheckbox(text: string) {
        return (text.includes(uncheckedCheckboxInputElement) || text.includes(checkedCheckboxInputElement))
    }
```

2024-04-09 13:53 UTC, eshankvaish commented on src/Common/CodeEditor/CodeEditor.tsx
> +                final = state.mode === 'json' ? JSON.stringify(obj, null, tabSize) : YAML.stringify(obj, { indent: 2 })
leave a todo

2024-04-09 13:56 UTC, eshankvaish commented on src/Common/Markdown/MarkDown.tsx
> +    }
.

2024-04-09 13:56 UTC, eshankvaish approved these changes

2024-04-10 02:20 UTC, vivek-devtron submitted a review, later dismissed

2024-04-10 02:51 UTC, vivek-devtron approved these changes

2024-04-12 06:09 UTC, vivek-devtron approved these changes

2024-04-12 06:40 UTC, vivek-devtron submitted a review, later dismissed

2024-04-12 08:11 UTC, vivek-devtron approved these changes

2024-05-20 05:16 UTC, shivani170 commented
Merged in demo/release

2024-05-20 05:16 UTC, closed without merging