feat/button with selector
devtron-labs/devtron-fe-common-lib pull request #128
Opened 2024-04-15 08:08 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-15 11:20 UTC, AbhishekA1509 requested changes

2024-04-15 11:20 UTC, AbhishekA1509 commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +                <ICDropdown className="icon-dim-12 fcn-0" />
Check if we can rotate arrow on open

2024-04-15 11:20 UTC, AbhishekA1509 commented on src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButon.tsx
> +        history.push(`releases/create`)
Can we use constant?

2024-04-15 11:20 UTC, AbhishekA1509 commented on src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButon.tsx
> +    const buttonClickHandlerFunc = (btnType: string) => {
can have better name, generally getter utils have prefix of get

2024-04-15 11:20 UTC, AbhishekA1509 commented on src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButon.tsx
> +    const dropdownOptions = (
Can make a separate component

2024-04-25 12:15 UTC, eshankvaish requested changes

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.scss
> +        border: 1px solid var(--N200)
- Pls check:
```suggestion
        border: 1px solid var(--N200);
```

- Also, the file name should be buttonWithSelector.scss

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.scss
> +.create-button-selector {
```suggestion
.button-with-selector {
```

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +                <ICDropdown className="icon-dim-12 fcn-0" />
also add transition

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +            <PopupMenu.Body>{menuItems}</PopupMenu.Body>
use children instead

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/types.ts
> +    buttonContent: string
```suggestion
    buttonContent: ReactNode
```

2024-04-25 12:15 UTC, eshankvaish commented on src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButton.scss
> +    box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.20);
Please update the styling, re-use the util ones. Don't directly copy from figma

2024-04-29 14:02 UTC, arunjaindev commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +            <PopupMenu.Body>{menuItems}</PopupMenu.Body>
lint error

2024-04-30 13:13 UTC, AbhishekA1509 commented on src/Shared/Components/ButtonWithSelector/index.ts
> +// eslint-disable-next-line import/prefer-default-export
verify if needed since have remove this rule after image promotion

2024-04-30 13:13 UTC, AbhishekA1509 commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +const ButtonWithSelector = ({ buttonContent, buttonClickHandler, menuItems }: ButtonWithSelectorProps) => {
Can add jsdoc comments for this?

2024-05-01 09:57 UTC, AbhishekA1509 approved these changes

2024-05-01 10:28 UTC, eshankvaish requested changes

2024-05-01 10:28 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> + * <ButtonWithSelector buttonContent='Create Job' buttonClickHandler={() => {}} children={<>dropdownOptions</>} />
```suggestion
 * <ButtonWithSelector buttonContent='Create Job' buttonClickHandler={() => {}}>
 *   {dropdownOptions}
 * </ButtonWithSelector>
```

2024-05-01 10:28 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +                className="cta flex h-28 dc__no-right-radius dc__no-border-imp fs-12 fw-6 lh-18"
leave a classname here pls. Also check if lh-18 is actually applied

2024-05-01 10:28 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/ButtonWithSelector.tsx
> +                className="cta flex h-28 dc__no-right-radius dc__no-border-imp fs-12 fw-6 lh-18"
add type for the button

2024-05-01 10:28 UTC, eshankvaish commented on src/Shared/Components/ButtonWithSelector/buttonWithSelector.scss
> +        border: 1px solid var(--N200)
```suggestion
        border: 1px solid var(--N200);
```

2024-05-02 07:53 UTC, merged