feat: add hook use download
devtron-labs/devtron-fe-common-lib pull request #209
Opened 2024-07-10 11:41 UTC by arunjaindev

# Description
Add hook useDownload to download files using blob objects

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-07-10 11:56 UTC, AbhishekA1509 requested changes

2024-07-10 11:56 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/index.tsx
> +export { default as useDownload } from './UseDownload'
I believe we should also export HandleDownloadProps

2024-07-10 11:56 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +            toast.error(error)
Can use showError

2024-07-10 11:56 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +            } else {
Check if we can move this else into catch block itself?

2024-07-10 11:56 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +            if (response.status === 200) {
Can use from api status code enum

2024-07-10 11:56 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +    downloadUrl: API url for downloading file
Please format

2024-07-10 13:31 UTC, AbhishekA1509 requested changes

2024-07-10 13:31 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +                showError(new Error(error))
Can we send jsonResponse itself in showError

2024-07-11 10:01 UTC, AbhishekA1509 approved these changes

2024-07-12 04:40 UTC, vivek-devtron submitted a review, later dismissed

2024-07-26 11:43 UTC, vivek-devtron submitted a review, later dismissed

2024-07-29 10:35 UTC, vivek-devtron approved these changes

2024-07-29 10:36 UTC, merged