feat: use useDownload globally
devtron-labs/devtron-fe-common-lib pull request #213
Opened 2024-07-12 12:17 UTC by arunjaindev

# Description
use useDownload Hook to download files/folders globally

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-07-18 11:35 UTC, AbhishekA1509 requested changes

2024-07-18 11:35 UTC, AbhishekA1509 commented on src/Shared/Hooks/UseDownload/UseDownload.tsx
> +                    'file.tgz'
Can create a method for this to get file name from response header

2024-07-19 06:45 UTC, AbhishekA1509 approved these changes

2024-07-19 07:39 UTC, AbhishekA1509 approved these changes

2024-07-19 10:23 UTC, vivek-devtron approved these changes

2024-07-26 11:46 UTC, merged