feat: security scan v1 modal
devtron-labs/devtron-fe-common-lib pull request #234
Opened 2024-08-02 11:57 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-07 09:32 UTC, AbhishekA1509 requested changes

2024-08-07 09:32 UTC, AbhishekA1509 commented on src/Common/Security/ScanVulnerabilitiesTable.tsx
> +    const [sortConfig, setSortConfig] = useState<SortConfig>({
Can use useStateFilters

2024-08-07 09:32 UTC, AbhishekA1509 commented on src/Common/Security/ScanVulnerabilitiesTable.tsx
> +                    className={`security-tab__table-header ${shouldStick ? 'dc__position-sticky bcn-0 dc__zi-4 dc__top-42' : ''}`}
This is a breaking change it should stick to top_0, if needed any other variant can specify a class to define top distance

2024-08-12 06:02 UTC, AbhishekA1509 commented on src/Common/SearchBar/SearchBar.component.tsx
> +                className={`search-bar ${noBackgroundAndBorder ? 'dc__no-border dc__no-background dc__hover-n50' : 'bc-n50 en-2 dc__hover-border-n300'} focus-within-border-b5 dc__block w-100 min-w-20
Suggestion ideally should be util with switch case in it

2024-08-12 06:05 UTC, AbhishekA1509 approved these changes

2024-08-12 06:53 UTC, vivek-devtron approved these changes

2024-08-12 07:04 UTC, merged