feat: migrate helm release
devtron-labs/devtron-fe-common-lib pull request #237
Opened 2024-08-07 08:42 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-09 07:19 UTC, AbhishekA1509 requested changes

2024-08-09 07:19 UTC, AbhishekA1509 commented on src/Pages/CDPipeline/types.tsx
> +export interface Environment {
Check if can use EnvListMinDTO

2024-08-09 07:19 UTC, AbhishekA1509 commented on src/Pages/CDPipeline/types.tsx
> +export interface PipelineBuildStageType {
can extend BuildStageType or we can update BuildStageType if same

2024-08-12 05:48 UTC, arunjaindev commented on src/Pages/CDPipeline/types.tsx
> +export interface Environment {
some keys are different

2024-08-12 05:50 UTC, AbhishekA1509 commented on src/Pages/CDPipeline/types.tsx
> +export interface Environment {
Can atleast Pick same types

2024-08-12 08:04 UTC, AbhishekA1509 approved these changes

2024-08-14 12:19 UTC, vivek-devtron approved these changes

2024-08-22 13:56 UTC, vivek-devtron approved these changes

2024-08-22 13:56 UTC, merged