refactor: move config-diff compare utils, types, services to common-lib
devtron-labs/devtron-fe-common-lib pull request #241
Opened 2024-08-09 10:07 UTC by RohitRaj011

# Description

Moved Config Diff Services, Utils & Types to common-lib

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-12 07:55 UTC, eshankvaish requested changes

2024-08-12 07:55 UTC, eshankvaish commented on src/Shared/Helpers.tsx
> +            if (!('value' in curr)) {
```suggestion
            if (!('options' in curr)) {
```

2024-08-12 07:55 UTC, eshankvaish commented on src/Shared/Helpers.tsx
> +export const getSelectPickerOptionByValue = (
We can move to select picker / utils

2024-08-12 08:42 UTC, eshankvaish approved these changes

2024-08-16 08:06 UTC, vivek-devtron approved these changes

2024-08-21 04:58 UTC, merged