feat: add support for multi select picket
devtron-labs/devtron-fe-common-lib pull request #244
Opened 2024-08-12 07:25 UTC by eshankvaish

# Description

- feat: add support for multi select picket

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-13 06:38 UTC, RohitRaj011 requested changes

2024-08-13 06:38 UTC, RohitRaj011 commented on src/Shared/Components/SelectPicker/index.ts
> +export { default as FilterSelectPicker } from './FilterSelectPicker'
export `getSelectPickerOptionByValue` as well

2024-08-13 06:38 UTC, RohitRaj011 commented on src/Shared/Components/SelectPicker/common.tsx
> +                ...selectedOptions.filter(
can common out the filter operation as it is being used on line 254 as well

2024-08-13 08:13 UTC, RohitRaj011 approved these changes

2024-08-23 07:02 UTC, vivek-devtron submitted a review, later dismissed

2024-08-23 09:20 UTC, vivek-devtron submitted a review, later dismissed

2024-08-23 09:30 UTC, vivek-devtron approved these changes

2024-08-23 09:30 UTC, merged