feat: TabGroup - add xl size variant, add description support
devtron-labs/devtron-fe-common-lib pull request #303
Opened 2024-09-13 10:49 UTC by RohitRaj011

# Description

feat: StatusFilterButton - UI update
feat: Drawer - onClose prop support

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-19 09:55 UTC, eshankvaish requested changes

2024-09-19 09:55 UTC, eshankvaish commented on src/Shared/Components/TabGroup/TabGroup.scss
> +                #{$parent-selector}__icon--stroke {
Check the implementation of Button for targetting the icon styling

2024-09-19 09:55 UTC, eshankvaish commented on src/Shared/Components/TabGroup/TabGroup.component.tsx
> +                              ))
Let's use ul/li

2024-09-20 10:56 UTC, eshankvaish approved these changes

2024-09-20 13:20 UTC, vivek-devtron commented on src/Shared/Components/TabGroup/TabGroup.component.tsx
> +                <p className="m-0 flexbox dc__align-items-center dc__gap-6">
We should extract this in a function so that condition cluttering can be removed

2024-09-20 13:48 UTC, vivek-devtron approved these changes

2024-09-20 14:00 UTC, vivek-devtron approved these changes

2024-09-20 14:01 UTC, merged