feat: Revamp ConfigMap Secret UI - Various Improvements
devtron-labs/devtron-fe-common-lib pull request #336
Opened 2024-10-06 17:22 UTC by RohitRaj011

# Description

  - getResolvedDeploymentTemplate service - add optional abort signal
  - DeploymentHistoryDiffView - remove default sorting, on load yaml will not be sorted
  - TabGroup - improved disabled state UI and logic
  - useForm - add new methods, improved logic and documentation
  - ConfigMapSecretDTO - improved types

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-08 07:58 UTC, AbhishekA1509 commented on src/Shared/Components/CICDHistory/DeploymentHistoryDiff/DeploymentHistoryDiffView.tsx
> +            key={`${sortBy}-${sortOrder}`}
TODO: Before merging needs to remove this since can collide

2024-10-08 09:01 UTC, AbhishekA1509 requested changes

2024-10-09 09:28 UTC, AbhishekA1509 approved these changes

2024-10-10 07:54 UTC, vivek-devtron approved these changes

2024-10-10 12:11 UTC, merged