feat: add support for local storage filters in use url filters
devtron-labs/devtron-fe-common-lib pull request #370
Opened 2024-10-25 06:44 UTC by arunjaindev

# Description
add support for local storage filters in use url filters

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-10-29 05:35 UTC, eshankvaish requested changes

2024-10-29 05:35 UTC, eshankvaish commented on src/Common/Hooks/useUrlFilters/useUrlFilters.ts
> +        localStorage.setItem(localStorageKey, '')
shouldn't we check if the localStorageKey exists? Better would be create a internal function for setting/getting/removing the item

2024-10-29 05:35 UTC, eshankvaish commented on src/Common/Hooks/useUrlFilters/useUrlFilters.ts
> +        localStorage.setItem(localStorageKey, JSON.stringify(parseSearchParams(searchParams)))
leave a comment mentioning that we are skipping the primary filters like page number, sorting etc.

2024-10-29 09:57 UTC, arunjaindev commented on src/Common/Hooks/useUrlFilters/useUrlFilters.ts
> +        ) {
Not clearing local storage so that we can store the filters and use for next visit.

2024-10-29 11:05 UTC, eshankvaish approved these changes

2024-10-29 13:24 UTC, eshankvaish submitted a review, later dismissed

2024-11-04 04:29 UTC, RohitRaj011 commented on src/Common/Hooks/useUrlFilters/utils.tsx
> +export const setItemInLocalStorageIfKeyExists = (localStorageKey: string, value: string) => {
future scope can be making a LocalStorage Util class

2024-11-04 04:30 UTC, RohitRaj011 approved these changes

2024-11-04 08:43 UTC, vivek-devtron submitted a review, later dismissed

2024-11-04 09:53 UTC, vivek-devtron submitted a review, later dismissed

2024-11-05 08:17 UTC, vivek-devtron approved these changes

2024-11-05 08:22 UTC, merged