feat: mandatory tags v2
devtron-labs/devtron-fe-common-lib pull request #424
Opened 2024-11-27 07:20 UTC by shivani170

# Description

Branch: feat/mandatory tags v2

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-06 11:00 UTC, RohitRaj011 commented on src/Common/CustomTagSelector/PropagateTagInfo.tsx
> +            placement="left"
this will impact other places as well, is it expected

2024-12-06 11:02 UTC, RohitRaj011 commented on src/Shared/Components/DynamicDataTable/DynamicDataTableRow.tsx
> +                                        className="icon-dim-16 fcn-4 dc__align-self-start icon-use-fill-n6"
remove this 
the icon will be replaced by ICCross

2024-12-06 11:05 UTC, RohitRaj011 requested changes

2024-12-06 11:05 UTC, RohitRaj011 commented on src/Shared/Components/DynamicDataTable/types.ts
> +    renderHelpTextForHeader?: () => ReactNode
can rename this to `renderAdditionalContent` and also update comment

2024-12-06 11:05 UTC, RohitRaj011 commented on src/Shared/Components/DynamicDataTable/types.ts
> +import { InfoIconTippyProps } from '@Common/Types'
is this being used?

2024-12-11 04:25 UTC, RohitRaj011 commented on src/Shared/Components/DynamicDataTable/DynamicDataTableRow.tsx
> +                    className={`dc__overflow-hidden flex top bcn-0 ${position === 'start' ? 'dc__bottom-left-radius' : 'dc__bottom-right-radius'}`}
while resolving conflicts discard these changes already handled this

2024-12-11 04:25 UTC, RohitRaj011 approved these changes

2024-12-11 04:26 UTC, RohitRaj011 commented
changes from @Elessar1802 PR are also showing please sync and verify

2024-12-11 11:44 UTC, vivek-devtron approved these changes

2024-12-19 14:39 UTC, vivek-devtron submitted a review, later dismissed

2024-12-19 14:50 UTC, vivek-devtron approved these changes

2024-12-20 07:41 UTC, vivek-devtron submitted a review, later dismissed

2024-12-20 12:32 UTC, vivek-devtron approved these changes

2024-12-20 12:33 UTC, AbhishekA1509 approved these changes

2024-12-20 12:33 UTC, merged