feat: add support for generic value configuration and target platform in build infra
devtron-labs/devtron-fe-common-lib pull request #427
Opened 2024-11-29 12:35 UTC by AbhishekA1509

# Description
feat: add support for generic value configuration and target platform in build infra

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-12-17 04:27 UTC, AbhishekA1509 commented on src/Shared/validations.tsx
> +export const validateTagValue = (value: string): string[] => {
Have moved these methods as is from ValidationRules of mandatory tags

2024-12-17 04:29 UTC, AbhishekA1509 commented on src/Shared/validations.tsx
> +        const re = new RegExp('/', 'g')
Ask if can use split itself here instead of regex?

2024-12-17 12:34 UTC, AbhishekA1509 commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +                    key: BuildInfraConfigTypes.CPU_LIMIT,
Have added key so that it can infer types

2024-12-18 06:50 UTC, eshankvaish requested changes

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/BuildInfraConfigForm.tsx
> +                                    isDefaultProfile={isGlobalProfile}
isGlobalProfile={isGlobalProfile}

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/BuildInfraFormAction.tsx
> +        })
suggestion: can create a common handler

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/constants.tsx
> +        (acc, field, index) => ({ ...acc, [index]: field }),
```suggestion
        (acc, field, index) => {
            acc[index] = field
            return acc
        },
```

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/constants.tsx
> +export const BUILD_INFRA_DEFAULT_PLATFORM_NAME = 'default' as const
```suggestion
export const BUILD_INFRA_DEFAULT_PLATFORM_NAME = 'default'
```

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +        const initialProfileInputErrors = { ...PROFILE_INPUT_ERROR_FIELDS }
let's use structured clone

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +    }
here as well

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +    if (!isDifferenceBigNumber) {
```suggestion
    const isDifferenceBigNumber = limitRequestUnitFactor * limitRequestFactor >= Number.MAX_SAFE_INTEGER

    if (isDifferenceBigNumber) {
```

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +                }
can be removed

2024-12-18 06:50 UTC, eshankvaish commented on src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
> +                }
Can be logged to sentry

2024-12-18 10:08 UTC, eshankvaish submitted a review, later dismissed

2024-12-26 12:45 UTC, vivek-devtron submitted a review, later dismissed

2024-12-26 13:34 UTC, vivek-devtron approved these changes

2024-12-26 13:38 UTC, merged