feat: add global approval policy and enforcement
devtron-labs/devtron-fe-common-lib pull request #428
Opened 2024-11-29 17:20 UTC by eshankvaish

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-05 10:00 UTC, AbhishekA1509 commented on src/Common/Types.ts
> +    approverList: {
Please move to interface

2024-12-05 10:02 UTC, AbhishekA1509 commented on src/Common/Types.ts
> +export enum ApprovalConfigDataKindType {
Please check with BE if we can extend existing enum of ConfigResourceType which is being used across protection flow

2024-12-05 10:07 UTC, AbhishekA1509 commented on src/Common/Types.ts
> +        userGroups: (UserApprovalInfo & {
Can move to interface since extending this below

2024-12-05 10:14 UTC, AbhishekA1509 commented on src/Common/Common.service.ts
> +            approverList: sanitizeUserApprovalList(deploymentApprovalInfo?.eligibleApprovers?.anyUsers?.approverList),
Please move deploymentApprovalInfo?.eligibleApprovers?.anyUsers?.approverList into variable

2024-12-05 10:46 UTC, AbhishekA1509 requested changes

2024-12-05 10:46 UTC, AbhishekA1509 commented on src/Common/Common.service.ts
> +    ...userApprovalMetadata,
Can de-structure null

2024-12-05 10:46 UTC, AbhishekA1509 commented on src/Shared/Components/CICDHistory/service.tsx
> +            ? `${ROUTES.APP}/cd-pipeline/workflow/trigger-info/${appId}/${envId}/${pipelineId}/${triggerId}${getTriggerDetailsQuery(fetchIdData)}`
Suggestion: `${ROUTES.APP}/cd-pipeline/workflow/trigger-info/${appId}/${envId}/${pipelineId} is constant and can we create route

2024-12-05 10:46 UTC, AbhishekA1509 commented on src/Shared/Components/CICDHistory/TriggerOutput.tsx
> +            const userApprovalMetadata = triggerHistory.get(syncTriggerId)?.userApprovalMetadata
Please ensure this is sanitized

2024-12-05 10:46 UTC, AbhishekA1509 commented on src/Shared/constants.tsx
> +export const BASE_CONFIGURATION_ENV_ID = -1
Had made this in DeploymentTemplate in dashboard please replace that as well

2024-12-05 10:47 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-13 10:30 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-24 10:40 UTC, vivek-devtron approved these changes

2024-12-27 06:01 UTC, vivek-devtron approved these changes

2024-12-27 06:02 UTC, merged