feat: add type for trigger block state due to mandatory tags
devtron-labs/devtron-fe-common-lib pull request #429
Opened 2024-12-02 09:47 UTC by arunjaindev

# Description
add type for trigger block state due to mandatory tags

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-02 11:48 UTC, AbhishekA1509 requested changes

2024-12-02 11:48 UTC, AbhishekA1509 commented on src/Common/Types.ts
> +    // Denotes trigger blocking due to mandatory tags, (might be used for plugins and other features in future)
Please use proper format to give comment

2024-12-02 11:48 UTC, AbhishekA1509 commented on src/Common/Types.ts
>      ConsequenceType,
Please remove unused import

2024-12-10 06:53 UTC, AbhishekA1509 requested changes

2024-12-10 06:56 UTC, AbhishekA1509 commented on src/Common/Common.service.ts
> +            deploymentBlockedState: material.deploymentBlockedState ?? null,
Please sanitize

2024-12-10 07:14 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-11 06:05 UTC, vivek-devtron approved these changes

2024-12-19 14:46 UTC, vivek-devtron approved these changes

2024-12-19 14:47 UTC, merged