feat: Runtime Params
devtron-labs/devtron-fe-common-lib pull request #443
Opened 2024-12-05 21:59 UTC by RohitRaj011

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-06 11:42 UTC, eshankvaish requested changes

2024-12-06 11:42 UTC, eshankvaish commented on src/Common/CIPipeline.Types.ts
> +export interface FileProperty {
Please add Type to the interfaces across PR

2024-12-06 11:42 UTC, eshankvaish commented on src/Common/CIPipeline.Types.ts
> +    refVariableUsed: boolean
Suggestion: Add ts docs to the types

2024-12-06 11:42 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/CDPipeline/services.ts
> +}): Promise<UploadFileDTO> => {
- allowedExtensions, maxUploadSize are already in one of the types. pls reuse
- abortControllerRef should be read from APIOptions

2024-12-06 11:42 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/CDPipeline/services.ts
> +        showError(err)
Not sure but i think we should throw the error even if it is aborted. Let me know if I'm missing something

2024-12-06 11:42 UTC, eshankvaish commented on src/Shared/Components/FileUpload/FileUpload.tsx
> +                        onClick={() => onUpload([])}
move the inline function

2024-12-06 11:42 UTC, eshankvaish commented on src/Shared/Components/FileUpload/FileUpload.tsx
> +        <div className={className || ''}>
We can remove the classname prop and wrap with a div

2024-12-09 10:30 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/CDPipeline/services.ts
> +}): Promise<UploadFileDTO> => {
abortControllerRef part seems to be left

2024-12-09 10:32 UTC, eshankvaish approved these changes

2024-12-09 10:32 UTC, eshankvaish commented on src/Shared/Components/DynamicDataTable/styles.scss
> +        &__select-picker__control {
is this class targeting correctly?

2024-12-09 16:56 UTC, RohitRaj011 commented on src/Shared/Components/DynamicDataTable/styles.scss
> +        &__select-picker__control {
yes

2024-12-16 06:40 UTC, vivek-devtron commented on src/Common/TippyCustomized.tsx
> +            stopPropagation(e)
Should this be outside of `if`?

2024-12-16 06:46 UTC, vivek-devtron approved these changes

2024-12-16 14:31 UTC, vivek-devtron approved these changes

2024-12-16 14:33 UTC, vikramdevtron approved these changes

2024-12-16 14:33 UTC, merged