chore: segmented bar updated for proportional
devtron-labs/devtron-fe-common-lib pull request #468
Opened 2024-12-19 04:55 UTC by shivani170

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-19 08:43 UTC, Elessar1802 requested changes

2024-12-19 08:43 UTC, Elessar1802 commented on src/Common/SegmentedBarChart/types.ts
> +    proportionalValue?: string
This prop is redundant since I am calculating total based on the value. Can discuss on this.

2024-12-19 08:43 UTC, Elessar1802 commented on src/Common/SegmentedBarChart/SegmentedBarChart.tsx
> +            {value}
```suggestion
            {isProportional ? `${value}/${total}` : value}
```

2024-12-20 10:45 UTC, RohitRaj011 requested changes

2024-12-20 10:45 UTC, RohitRaj011 commented on src/Common/SegmentedBarChart/SegmentedBarChart.tsx
> +            return entities?.map((entity) => {
is `?` necessary?

2024-12-20 10:45 UTC, RohitRaj011 commented on src/Common/SegmentedBarChart/SegmentedBarChart.tsx
> +                if (entity.value === 0) {
can filter out null values first and then run map

2024-12-20 11:10 UTC, Elessar1802 approved these changes

2024-12-22 14:07 UTC, RohitRaj011 approved these changes

2024-12-23 06:22 UTC, vivek-devtron approved these changes

2024-12-23 06:33 UTC, vivek-devtron approved these changes

2024-12-23 06:36 UTC, merged