feat: add animated button for cd modal
devtron-labs/devtron-fe-common-lib pull request #474
Opened 2024-12-20 08:13 UTC by arunjaindev

# Description
add animated button for cd modal

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-20 11:43 UTC, AbhishekA1509 requested changes

2024-12-20 11:43 UTC, AbhishekA1509 commented on src/Shared/Components/AnimatedDeployButton/AnimatedDeployButton.tsx
> +            {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
Check if aria-label will help

2024-12-20 12:06 UTC, arunjaindev commented on src/index.ts
> +    FEATURE_ACTION_AUDIOS_ENABLE?: boolean
this is generic flag for audios throughout dashboard

2024-12-20 12:34 UTC, AbhishekA1509 commented on src/Shared/Components/AnimatedDeployButton/AnimatedDeployButton.tsx
> +        clearTimeout(timeoutRef.current)
I believe this must be unintentional

2024-12-20 12:38 UTC, AbhishekA1509 commented on src/Shared/Components/AnimatedDeployButton/AnimatedDeployButton.tsx
> +            await audioRef.current.play()
If async do we need to handleError

2024-12-20 13:10 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-23 13:51 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-24 09:01 UTC, vivek-devtron approved these changes

2024-12-24 09:52 UTC, vivek-devtron approved these changes

2024-12-24 09:53 UTC, merged