chore: add type for isLinkedCD in node attr
devtron-labs/devtron-fe-common-lib pull request #48
Opened 2023-11-16 07:39 UTC by AbhishekA1509

Adding type of isLinkedCD in node attr and opening up prop for autoFocus in DebouncedSearch.

2023-11-20 13:24 UTC, eshankvaish requested changes

2023-11-20 13:27 UTC, AbhishekA1509 commented on src/Common/DebouncedSearch/DebouncedSearch.tsx
> +                autoFocus={autoFocus}
In Plan would do whenever have time

2023-11-21 07:48 UTC, AbhishekA1509 commented on src/Common/Dialogs/DeleteDialog.tsx
> +    }
Done

2023-11-21 07:49 UTC, eshankvaish approved these changes

2023-11-27 12:27 UTC, vivek-devtron approved these changes

2023-11-28 05:49 UTC, merged