feat: add VirtualizedList component
devtron-labs/devtron-fe-common-lib pull request #486
Opened 2024-12-27 13:20 UTC by RohitRaj011

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-12-31 07:40 UTC, AbhishekA1509 requested changes

2024-12-31 07:45 UTC, RohitRaj011 commented on src/Shared/Components/VirtualizedList/VirtualizedList.types.ts
> +        AutoSizedStickyTreeProps<VirtualizedListItem<ListKeys, ExtendedType>>,
discussed

2024-12-31 07:46 UTC, RohitRaj011 commented on src/Shared/Components/NumbersCount/types.ts
> -    isSelected?: boolean
discussed

2024-12-31 08:01 UTC, AbhishekA1509 approved these changes

2025-01-03 11:25 UTC, vivek-devtron submitted a review, later dismissed

2025-01-13 06:21 UTC, merged