feat: bulk trigger deployment in DA workflow
devtron-labs/devtron-fe-common-lib pull request #489
Opened 2024-12-31 14:31 UTC by Elessar1802

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] Does this PR require documentation updates?
- [ ] I've updated documentation as required by this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2025-01-03 07:07 UTC, AbhishekA1509 commented on src/Common/Common.service.ts
> +        userApprovalConfig: cdMaterialsResult.userApprovalConfig ?? null
Do we need to sanitize it?

2025-01-06 16:35 UTC, Elessar1802 commented on src/Common/Common.service.ts
> +        userApprovalConfig: cdMaterialsResult.userApprovalConfig ?? null
migrated the `sanitizeUserApprovalConfig` to common-lib from fe-lib

2025-01-07 07:03 UTC, eshankvaish requested changes

2025-01-07 07:03 UTC, eshankvaish commented on src/Shared/Components/BulkOperations/BulkOperations.component.tsx
> +    }
let's stick to standard method

2025-01-08 08:10 UTC, eshankvaish approved these changes

2025-01-08 11:06 UTC, vivek-devtron submitted a review, later dismissed

2025-01-13 07:33 UTC, vivek-devtron approved these changes

2025-01-13 07:33 UTC, merged